apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: app4
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.io/dmassaro/app4:patest # {"$imagepolicy": "flux-system:app-05"}
        name: nginx
