apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-05
  namespace: flux-system
spec:
  interval: 5m
  path: "./kubernetes/deployment/"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true