apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app-05
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: app-05
  filterTags:
    pattern: "^(?P<timestamp>.*)$"
    extract: "$ts"
  policy:
    alphabetical:
      order: asc
