apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: app-05
  namespace: flux-system
spec:
  interval: 1m0s
  image: docker.io/dmassaro/app4
  secretRef:
    name: regcred
